clear; close all; clc;

%% Figure 1: Spatial Distribution Map (3 Zones)
figure('Position',[100 100 800 600]);
hold on; grid on;
xlim([0 2]); ylim([0 2]);
% Zone A (Left Residential: 0-0.6km)
fill([0 0.6 0.6 0],[0 0 2 2],[0.8 0.9 1],'EdgeColor','k','FaceAlpha',0.3);
text(0.3, 1, {'Zone A','Left Residential'}, ...
    'HorizontalAlignment','center', ...
    'FontSize',12, ...
    'FontWeight','bold');

% Zone B (Central Road: 0.6-1.4km) 
fill([0.6 1.4 1.4 0.6],[0 0 2 2],[1 0.9 0.7], ...
     'EdgeColor','k','FaceAlpha',0.4);

text(1, 1, {'Zone B','Central Road','(Transient Users)'}, ...
     'HorizontalAlignment','center', ...
     'FontSize',12, ...
     'FontWeight','bold');

% Zone C (Right Residential: 1.4-2km)
fill([1.4 2 2 1.4],[0 0 2 2],[0.7 0.9 0.8], ...
     'EdgeColor','k','FaceAlpha',0.3);

text(1.7, 1, {'Zone C','Right Residential'}, ...
     'HorizontalAlignment','center', ...
     'FontSize',12, ...
     'FontWeight','bold');

title('Figure 1: Spatial Distribution Map (2km x 2km Area)','FontSize',14,'FontWeight','bold');
xlabel('X (km)'); ylabel('Y (km)');
legend('Residential','Road Corridor','Residential','Location','northeast');
